### ISSUE TITLE
Autosave intermittency

### ISSUE THREAD

**Issue by ludwa6** [Jermolene/tiddlywiki-on-fission#4]
It seems that -although TW on Fission routinely saves its state following an edit- sometimes it doesn't... And then if i push the TW "Save" control (with checkmark indicating red) it will revert to an earlier state, resulting in loss of subsequent edits -including changes that i had thought were saved, based on both (a) red checkmark turning black/ "saved wiki" message in top RH corner of window; and (b) the read-only version at {username}.files.fission.name/p/{wikiname}.html reflecting these changes.  

Workaround for now is: i make point of avoiding both the red checkmark "save" control, and the refresh button, which i have hidden... And if i go on and make some more edits, at some point the autosave feature eventually kicks in, tho i don't know either what causes it to stall, nor what finally triggers it.  Maybe it's just a timing thing?

Anyway: I'd like to know if anyone else can replicate this problem and/or suggest a plausible theory of cause.

I'm editing via latest Chrome browser (Version 89.0.4389.90 Official Build x86_64) on Mac OS High Sierra (10.13.6).

**Comment by Jermolene** [comment]
Thanks @ludwa6 

> It seems that -although TW on Fission routinely saves its state following an edit- sometimes it doesn't...

Ouch! Your help tracking down problems like this is much appreciated.

> And then if i push the TW "Save" control (with checkmark indicating red) it will revert to an earlier state, resulting in loss of subsequent edits -including changes that i had thought were saved, based on both (a) red checkmark turning black/ "saved wiki" message in top RH corner of window; and (b) the read-only version at {username}.files.fission.name/p/{wikiname}.html reflecting these changes.  

Wow, that's seriously strange. Has that happened regularly?

> Workaround for now is: i make point of avoiding both the red checkmark "save" control, and the refresh button, which i have hidden... And if i go on and make some more edits, at some point the autosave feature eventually kicks in, tho i don't know either what causes it to stall, nor what finally triggers it.  Maybe it's just a timing thing?

There may indeed be a timing issue, with old edits getting somehow overlapped with current ones.

I would expect that the only difference between relying on autosave and using the "save changes" button explicitly would indeed be a matter of timing.

> Anyway: I'd like to know if anyone else can replicate this problem and/or suggest a plausible theory of cause.

I'll continue to do more testing but I haven't been able to replicate this so far.

**Comment by ludwa6** [comment]
> Wow, that's seriously strange. Has that happened regularly?

It was happening often enough, the process of making and saving edits directly through the browser was not fun -moreover, i hate having to repeat a lot of keystrokes- and so my workflow now is to do all editing in TiddlyDesktop, export as JSON when i'm done the editing session, drag&drop that file into my TW-on-Fission file, and that's it.  So far this has worked great, and is moreover better aligned with [Local-First values](https://groups.google.com/g/tiddlywiki/c/f0J6pPpmkAs/m/SVXOyATmAAAJ).  

In fact: it was my understanding that this move to Fission backend would manifest as a local volume on my machine that is synced to the cloud somehow.  Is that scenario on the development roadmap, i wonder?

**Comment by bmann** [comment]
@ludwa6 we covered this on the call today. LocalStorage is a specific browser API term, as are other things like IndexedDB that aren't really user accessible: the data is in your browser, locally.

Separately -- if you install what is today the Fission developer command line tool, you can expect that files are also synced to desktop: your WebNative File System is then available everywhere.

And no, I haven't seen your issues in practice -- saving mostly just works. We ARE improving various parts of the Fission infrastructure, so you may have hit a bad patch a couple of days ago.

I'm going to go ahead and close this in a couple of days unless we can replicate. Thank you for testing!

**Comment by ludwa6** [comment]
As i haven't experienced it since what may well have been just a "bad patch" as you say, Boris, i agree w/ your decision to close the issue. 

Still: it would be nice to know if there's a way to recover edits that the Fission server has somehow lost, so i must ask, about this LocalStorage: sounds (to my non-devloper mind) like a browser cache, which i understand conceptually... But, practically speaking, is this a datastore from which i might conceivably recover an edit that the Fission server has failed to retain (even if not normally "user accessible")?

As to file sync via "Fission developer command line tool" : as my workflow is now editing in TiddlyDesktop, and only pushing from there to TiddlyFission, there is no need of this at present... But it's nice to know that tool exists, thanks!

**Comment by bmann** [comment]
The short answer is that in the default mode, Webnative stores everything locally, so at worst the content isn't available online. If you come back to the same browser, it should then attempt to sync. I think I can make a more specific issue around that, Jeremy is doing the syncing in a creative way so this may not be possible. Thanks for filing and discussing!
