### ISSUE TITLE
Read only public link missing a slash

### ISSUE THREAD

**Issue by bmann** [Jermolene/tiddlywiki-on-fission#6]
`https://boris20210213.files.fission.name/p/20210228index.html` is what shows, when it should be `https://boris20210213.files.fission.name/p/20210228/index.html`

**Comment by Jermolene** [comment]
Thanks @bmann, fixed in 9eda3314be51ddf29b19ae6479afc897b6390cf6

**Comment by bmann** [comment]
Sorry, looks like there is a double slash now for those files in the root public folder `https://boris20210213.files.fission.name/p//tiddlywiki.html`

Subfolder files have the correct slashes.
